Github issue 310: passing password via stdin was not working
* added a option to pass the string via cmdline (optional, not used by plinth) if called manually
* changed method of optional passing strings via stdin
* use a timeout if possible to avoid deadlocks
* handle ancient versions of read
* fix problem: if -p option was not the last given option, everything after -p was lost

diff --git a/actions/dynamicdns b/actions/dynamicdns
--- a/actions/dynamicdns
+++ b/actions/dynamicdns
@@ -64,8 +64,8 @@ doGetOpt()
 {
     basicauth=0
     ignoreCertError=0
-
-    while getopts ":s:d:u:p:I:U:c:b:" opt; do
+    stdin=0
+    while getopts ":s:d:u:P:I:U:c:b:p" opt; do
         case ${opt} in
             s)
                 if [ "${OPTARG}" != "${EMPTYSTRING}" ];then
@@ -80,10 +80,11 @@ doGetOpt()
             u)
                 user=${OPTARG}
             ;;
+            P)
+                pass=${OPTARG}
+            ;;
             p)
-                if read -t 0; then
-                    IFS= read -r pass
-                fi
+                stdin=1
             ;;
             I)
                 if [ "${OPTARG}" != "${EMPTYSTRING}" ];then
@@ -111,6 +112,21 @@ doGetOpt()
             ;;
         esac
     done
+    if [ $stdin -eq 1 ];then
+        # try to use with timeout and hidden input first
+        read -s -p "enter password and hit [ENTER]: " -t 10 password
+        RET=$?
+        # return 142 means: timeout
+        if [ -z ${password} -a ${RET} -ne 142 ];then
+            # ancient bash version does not support timeouts or hidden input
+            read -p "enter password and hit [ENTER]: " password
+        fi
+        if [ ${RET} -eq 142 ];then
+            echo "Failed to read password from stdin, try -P instead"
+            exit 1
+        fi
+        pass=${password}
+    fi
 }
 
 # this function will write a persistent config file to disk
@@ -293,7 +309,7 @@ doGetWANIP()
 doUpdate()
 {
     local dnsentry=$(nslookup "${host}"|tail -n2|grep A|sed s/[^0-9.]//g)
-    if [ "${dnsentry}" =  "${wanip}" ];then
+    if [ "${dnsentry}" = "${wanip}" ];then
         return
     fi
     if [ ! -z "${server}" ];then
@@ -428,6 +444,7 @@ case ${cmd} in
         echo "-s <server>             Gnudip Server address"
         echo "-d <domain>             Domain to be updated"
         echo "-u <user>               Account username"
+        echo "-P <password>           Account password"
         echo "-p                      Read Account Password from stdin"
         echo "-I <IP check URL>       A URL which returns the IP of the client who is requesting"
         echo "-U <update URL>         The update URL (a HTTP GET on this URL will be done)"
