users: Handle errors better during POSIX user operations
- If during an action, user does not exist ignore.

- If during an action, return a non-zero exist status.

- Catch an errors during actions as exceptions.

- Display a message that corresponding POSIX operation failed.

diff --git a/actions/enable-user b/actions/enable-user
--- a/actions/enable-user
+++ b/actions/enable-user
@@ -20,7 +20,14 @@
 
 username="$1"
 
+getent passwd "$username"
+if [ $? -ne 0 ]; then
+    echo "Failed: user not found"
+    exit
+fi
+
 usermod --expiredate "" "$username"
 if [ $? -ne 0 ]; then
     echo "Failed"
+    exit 2
 fi
