Show error messages from xmpp-setup and xmpp-register. Avoid causing plinth to show error page.

diff --git a/actions/xmpp-setup b/actions/xmpp-setup
--- a/actions/xmpp-setup
+++ b/actions/xmpp-setup
@@ -58,5 +58,5 @@ if [ "$xmpp_inband_enable" != "$xmpp_inband_enable_cur" ] ; then
     else
         sed -i s/"ip_access: all"/"ip_access: trusted_network"/ /etc/ejabberd/ejabberd.yml
     fi
-    ejabberdctl restart
+    ejabberdctl restart || echo "Failed to restart ejabberd with new configuration."
 fi
